### PR TITLE
スキンのフォントと画像が "filter":1 で linear filtering に対応するようになります

### PR DESCRIPTION
**Pull request by 5argon**
( SkinObject.java:389 にコメントされた部分も見つけたけど、過去に問題があったかわからないです。)

### CODE REVIEW

**Comment by exch-bms2** [comment]
Linear filtering for skin image has a problem that drawing image works incorrectly. Show this screenshot, and you can find unexpected lines around a song progress bar, and judge images.
So I commented out these lines.

**Comment by 5argon** [comment]
Hello. Can you lend me the play skin for testing?

**Comment by exch-bms2** [comment]
For example, spdframe, OADX, etc. Most of LR2 skins use linear filtering and you can find testing samples easily.

**Comment by 5argon** [comment]
Ok I understand the problem. It is that the textures are in straight alpha and linear filtering averages the "color" in the transparent pixel (which might be any color but you can't see it) to the opaque pixel. I think solution is to use premultiplied alpha for texture then also update the blending to PMA as well (`ONE, ONE_MINUS_SRC_ALPHA`). I have added one more commit to the PR.

Since all the skin texture are in straight alpha and premultiplying the image file is not convenient, I add a method that multiply alpha when the game loads those image. 

Using the default LR2 skin with linear filtering I got green pixels (.tga might have transparent pixel as (0,255,0,0)) but after the fix the artifact disappeared. I am not sure if it might also fix the problem on your skin or not.

screenshot 2017-10-26 18 06 24

screenshot 2017-10-27 00 22 15

**Comment by exch-bms2** [comment]
Thanks for your PR. I've confirmed that linear filtering works correctly in spdframe. However, I wonder if linear filtering can be processed without pre-converting skin images : it may cause another problems. So I'll try to re-factor this by using GLSL.
https://www.codeproject.com/Articles/236394/Bi-Cubic-and-Bi-Linear-Interpolation-with-GLSL

**Pull request merged**
