### PR TITLE
Upgrade to libgdx 1.11.0 and LWJGL 3.3.1 to fix Mac crash

### PR DESCRIPTION
**Pull request by mlaux**
This PR updates the project to libgdx 1.11.0 and LWJGL 3.3.1, fixing a crash on macOS 10.15 and above with certain combinations of JDK and JavaFX versions:

```
Process:               java [68856]
Path:                  /Library/Java/JavaVirtualMachines/jdk1.8.0_361.jdk/Contents/Home/bin/java
Identifier:            java
Version:               1.0 (1.8.0_361)
Code Type:             X86-64 (Native)
Parent Process:        idea [33033]
Responsible:           idea [33033]
User ID:               501

Date/Time:             2023-02-08 22:34:25.349 -0600
OS Version:            Mac OS X 10.15.7 (19H1615)
Report Version:        12
Anonymous UUID:        FDD76A0F-A9AC-47AD-2799-06700F5E0B24

Sleep/Wake UUID:       2454E68D-C922-4038-A1BF-9C1675CDB6BB

Time Awake Since Boot: 1800000 seconds
Time Since Wake:       2400 seconds

System Integrity Protection: enabled

Crashed Thread:        43  Java: LWJGL Application

Exception Type:        EXC_BAD_INSTRUCTION (SIGABRT)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
-[NSOpenGLContext setView:] must be called from the main thread.

Thread 43 Crashed:: Java: LWJGL Application
0   libsystem_kernel.dylib        	0x00007fff7142533a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff714e5e60 pthread_kill + 430
2   libsystem_c.dylib             	0x00007fff713ac808 abort + 120
3   libjvm.dylib                  	0x000000011008fa24 os::abort(bool) + 22
4   libjvm.dylib                  	0x000000011019dd4b VMError::report_and_die() + 2245
5   libjvm.dylib                  	0x00000001100940bf JVM_handle_bsd_signal + 500
6   libjvm.dylib                  	0x0000000110091ca3 signalHandler(int, __siginfo*, void*) + 45
7   libsystem_platform.dylib      	0x00007fff714da5fd _sigtramp + 29
8   ???                           	0x0000000000000002 0 + 2
9   liblwjgl.dylib                	0x0000000136745c77 Java_org_lwjgl_opengl_MacOSXContextImplementation_setView + 183
10  ???                           	0x00000001118ad747 0 + 4589279047
11  ???                           	0x000000011189d33d 0 + 4589212477
12  ???                           	0x000000011189d382 0 + 4589212546
13  ???                           	0x000000011189d33d 0 + 4589212477
14  ???                           	0x000000011189d382 0 + 4589212546
15  ???                           	0x000000011189d33d 0 + 4589212477
16  ???                           	0x000000011189d33d 0 + 4589212477
17  ???                           	0x000000011189d33d 0 + 4589212477
18  ???                           	0x000000011189d33d 0 + 4589212477
19  ???                           	0x000000011189d33d 0 + 4589212477
20  ???                           	0x000000011189d33d 0 + 4589212477
21  ???                           	0x000000011189d33d 0 + 4589212477
22  ???                           	0x0000000111895827 0 + 4589180967
23  libjvm.dylib                  	0x000000010fed7fab JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*) + 1673
24  libjvm.dylib                  	0x000000010fed6e0e JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*) + 330
25  libjvm.dylib                  	0x000000010fed6fef JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*) + 87
26  libjvm.dylib                  	0x000000010ff44213 thread_entry(JavaThread*, Thread*) + 120
27  libjvm.dylib                  	0x00000001101625f0 JavaThread::thread_main_inner() + 130
28  libjvm.dylib                  	0x00000001101624af JavaThread::run() + 413
29  libjvm.dylib                  	0x000000011008f55b java_start(Thread*) + 250
30  libsystem_pthread.dylib       	0x00007fff714e6109 _pthread_start + 148
31  libsystem_pthread.dylib       	0x00007fff714e1b8b thread_start + 15
``` 

I've played a few songs and graphics, audio, and input all seem to be working correctly. Further testing would be appreciated!

### CODE REVIEW

**Comment by staticssleever668** [comment]
@mlaux, hi, how do you compile beatoraja? This breaks the ant build script as dependency file paths haven't been updated there. Did you forget to stage build.xml by any chance?
Honestly though, I hate seeing this merged, as updating binary files bloats the repository size *a lot*. Although the fact the repo contained dependencies as binaries in the fist place is at fault. I think #714 is what should have been merged instead.

**Comment by wcko87** [comment]
I have the exact same thoughts as @staticssleever668
The jar file is also at least twice as large if you updated the dependencies in the ant build script.

**Comment by exch-bms2** [comment]
Reverted.
I just tested this PR (with modyfied build.xml), and trying to play, but controller doesn't work.
Please ensure that controller works on your environment.

**Comment by Getaji** [comment]
The problem with the controller not being detected seems to be due to the fact that it is not registered in the mapping managed by the backend, SDL. The actual problem may be simpler or more complex, but in my environment I solved it by generating and registering mappings.

There are several ways to register mappings, you can add the mapping string generated by the [SDL2 Gamepad Tool](https://generalarcade.com/gamepadtool/) or Steam's Big Picture mapping function to the `gdx-controllers-desktop.jar` file, or you can specify it in the environment variable `SDL_GAMECONTROLLERCONFIG`.

However, it would not be realistic for the developer to cover all the controllers that the user might connect, and it is not a good idea to make the user configure complicated settings. There may be some way to do this, as it was previously recognized without doing anything, but it may be unavoidable to maintain the use of the latest libGDX.

This is all I have been able to research. I hope this is helpful.

**Comment by hwsmm** [comment]
This PR also fixes a problem where `;` + Right Shift can't be pressed at the same time on Linux, I'd test and try fixing if I had a controller, but I don't have any sadly...

**Pull request merged**
